name: Sync Youki Crates

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * 0'  

jobs:
  sync-crates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rk8s repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch latest youki repository
        run: |
          git remote add youki https://github.com/youki-dev/youki.git
          git fetch youki

      - name: Sync libcontainer from youki
        run: |
          git checkout youki/main -- crates/libcontainer
          rsync -a --delete crates/libcontainer/ project/libcontainer/
          rm -rf crates/libcontainer  
          git add project/libcontainer
          git commit -m "Sync libcontainer from youki" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Sync libcgroups from youki
        run: |
          git checkout youki/main -- crates/libcgroups
          rsync -a --delete crates/libcontainer/ project/libcgroups/
          rm -rf crates/libcgroups  
          git add project/libcgroups
          git commit -m "Sync libcgroups from youki" || echo "No changes to commit"
          git push || echo "No changes to push"
