name: Sync Youki Crates

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * 0'  

jobs:
  sync-crates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rk8s repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch latest youki repository
        run: |
          git remote add youki https://github.com/youki-dev/youki.git
          git fetch youki

      - name: Sync libcontainer from youki
        run: |
          git checkout youki/main -- crates/libcontainer
          git mv crates/libcontainer /project/libcontainer || true
          git add /project/libcontainer
          git commit -m "Sync libcontainer from youki"
          git push

      - name: Sync libcgroups from youki
        run: |
          git checkout youki/main -- crates/libcgroups
          git mv crates/libcgroups /project/libcgroups || true
          git add /project/libcgroups
          git commit -m "Sync libcgroups from youki"
          git push
